Feature/hnj 10 creating header markup
zarinaazamatova/huawei_nextjs pull request #15
Opened 2023-07-04 10:19 UTC by zarinaazamatova

2023-07-04 14:38 UTC, Alex-2kZharkov commented
@zarinaazamatova Please don't forget to change commit descriptions

![image](https://github.com/zarinaazamatova/huawei_nextjs/assets/66321831/d54b3776-507b-4934-b78e-db2c04c7d15f)

2023-07-04 15:12 UTC, Alex-2kZharkov requested changes

2023-07-04 15:12 UTC, Alex-2kZharkov commented on src/components/Header/header.styles.ts
> +export const StyledDivLacation = styled.div`
`StyledLocation`

2023-07-04 15:12 UTC, Alex-2kZharkov commented on src/components/Header/header.styles.ts
> +export const StyledDivTop = styled.div`
Please, remove `DivPrefix`, it does not add any value

2023-07-04 15:12 UTC, Alex-2kZharkov commented on src/components/Header/header.styles.ts
> +    font-weight: 300;
`300` should come from the `theme` object

2023-07-04 15:12 UTC, Alex-2kZharkov commented on src/components/Header/header.styles.ts
> +    font-weight: 600;
`600` should come from the theme object

2023-07-04 15:12 UTC, Alex-2kZharkov commented on src/components/Header/header.styles.ts
> +  font-size: 7px;
Same thing: use `theme` object for the size of Fonts

2023-07-04 15:12 UTC, Alex-2kZharkov commented on src/components/Header/header.styles.ts
> +  margin: 0px 80px 0px 80px;
use shorter version `margin: 0px 80px;`

2023-07-04 15:12 UTC, Alex-2kZharkov commented on src/components/Header/header.styles.ts
> +		margin 10px 0 10px 0;
use shorter version `margin: 10px 0px;`

2023-07-04 15:12 UTC, Alex-2kZharkov commented on src/components/Header/header.styles.ts
> +export const StyledUl = styled.ul`
`StyledList`

2023-07-04 15:12 UTC, Alex-2kZharkov commented on src/components/Header/header.styles.ts
> +export const StyledLi = styled.li`
`StyledListItem`

2023-07-04 15:12 UTC, Alex-2kZharkov commented on src/components/Header/header.styles.ts
> +  font-weight: 600;
`theme` object

2023-07-04 15:12 UTC, Alex-2kZharkov commented on src/components/Header/header.tsx
> +            style={{ padding: '5px' }}
All of these inline styles should be used, ok, you will fix in the next task

2023-07-04 16:57 UTC, zarinaazamatova commented on .vscode/settings.json
✅

2023-07-05 20:47 UTC, zarinaazamatova commented on src/assets/png/logo.png
✅

2023-07-05 20:47 UTC, zarinaazamatova commented on src/assets/png/cart.png
✅

2023-07-05 20:48 UTC, zarinaazamatova commented on src/assets/svg/geolacation.tsx
> +const Geolocation = ({ width, height }: { width: number; height: number }) => {
✅

2023-07-05 20:48 UTC, zarinaazamatova commented on src/assets/svg/geolacation.tsx
> +export default Geolocation;
✅

2023-07-05 20:48 UTC, zarinaazamatova commented on src/components/Header/header.tsx
> +        <S.StyledDivLacation>
✅

2023-07-05 20:48 UTC, zarinaazamatova commented on src/components/Header/header.tsx
> +        <S.StyledDivBonusSide>
✅

2023-07-05 20:48 UTC, zarinaazamatova commented on src/components/Header/header.tsx
> +        <S.StyledDivCatalog>
✅

2023-07-05 20:49 UTC, zarinaazamatova commented on src/components/Header/header.tsx
> +        <S.StyledDivUserInfo>
✅

2023-07-05 20:49 UTC, zarinaazamatova commented on src/components/Header/header.tsx
> +            style={{ padding: '5px' }}
✅

2023-07-06 19:44 UTC, Alex-2kZharkov approved these changes
Excellent job! It was hard but you made it. Keep it up🙌

2023-07-07 14:39 UTC, merged