Feature/hnj 13 implement general news page
zarinaazamatova/huawei_nextjs pull request #18
Opened 2023-07-17 21:29 UTC by zarinaazamatova

2023-07-18 18:16 UTC, Alex-2kZharkov requested changes

2023-07-18 18:16 UTC, Alex-2kZharkov commented on src/components/News/News.tsx
> +  const handlePageChange = (selectedPage: any) => {
https://github.com/zarinaazamatova/huawei_nextjs/assets/66321831/8963215e-d050-4730-a315-a39927acb161

2023-07-18 18:16 UTC, Alex-2kZharkov commented on src/components/News/News.tsx
> +  const handlePageChange = (selectedPage: any) => {
set `void` as a return type for this function

2023-07-18 18:16 UTC, Alex-2kZharkov commented on src/components/News/News.tsx
> +    async function fetchData() {
set `Promise<void>` as a return type for this funtion

2023-07-18 18:16 UTC, Alex-2kZharkov commented on src/components/News/News.tsx
> +        <Link href="./" style={{ textDecoration: 'none', color: 'grey', fontSize: '12px' }}>
We discussed that we won't such things with inline `style`. Instead do it like so: 
```
styled(Link):
` 
textDecoration: 'none', 
color: 'grey', 
fontSize: '12px'
`
```

And it should work as well

2023-07-18 18:16 UTC, Alex-2kZharkov commented on src/components/News/News.tsx
> +          {news.map((e: any) => (
it should be `any` because you set it above to `NewsItem[]`, so it is of type of `NewsItem`

2023-07-18 18:16 UTC, Alex-2kZharkov commented on src/components/News/News.tsx
> +          {news.map((e: any) => (
+ use destucturing to extract `id, img, title` and skip `e.` (by the way, `e` is not suitable for this name, at least `news`)

2023-07-18 18:16 UTC, Alex-2kZharkov commented on src/components/News/News.tsx
> +  const pageSize: number = 16;
`16` and `48` such numbers called `magic numbers` becuase we don't know really why 16 and 48. The solution is to create 2 constants `DEFAULT_NEWS_PER_PAGE` and `NEWS_TOTAL`. Create these 2 variables `News.constants.ts` file, then import them here and use them instead of `pageSize` and `totalNews`

2023-07-18 18:16 UTC, Alex-2kZharkov commented on src/components/News/Pagination/Pagination.tsx
> +  onPageChange: any;
not `any`. Ask yourself: 

- what is it? It is a function. 
- So how do I say it is a function? `(someParams) => {}`
- What concreate arguments? `(selectedItem: { selected: number }) => `
- what does it return? it returns nothing, so `void`, `(selectedItem: { selected: number }) => void`

2023-07-18 18:16 UTC, Alex-2kZharkov commented on src/components/News/Pagination/Pagination.tsx
> +export const Pagination = ({ pageCount, onPageChange, selectedPage }: PaginationProps) => {
Use `ReactElement` from `react` for the component return type (turns out that JSX.Element is deprecated now)

2023-07-18 18:16 UTC, Alex-2kZharkov commented on src/components/News/News.tsx
> +export const News = () => {
Use `ReactElement` from `react` for the component return type (turns out that JSX.Element is deprecated now)

2023-07-18 18:16 UTC, Alex-2kZharkov commented on src/pages/index.tsx
> +  return <Layout />;
here you will have `<Layout> <News/> </Layout>`

2023-07-19 21:57 UTC, zarinaazamatova commented on src/components/Layout/Layout.tsx
> +      <News />
  ✅

2023-07-19 21:58 UTC, zarinaazamatova commented on src/components/Layout/index.tsx
✅

2023-07-19 22:02 UTC, zarinaazamatova commented on src/components/News/News.styles.ts
> +  margin-bottom: 30px;
🔥corrected everywhere

2023-07-19 22:03 UTC, zarinaazamatova commented on src/components/News/News.test.tsx
> +  it('should render news when api respond', async () => {
✅

2023-07-19 22:06 UTC, zarinaazamatova commented on src/components/News/News.test.tsx
> +    expect(
✅

2023-07-19 22:12 UTC, zarinaazamatova commented on src/components/News/News.tsx
> +  const [news, setNews] = useState<NewsItem[]>([]);
Got it✅ Thank you

2023-07-19 22:15 UTC, zarinaazamatova commented on src/components/News/News.tsx
> +  const handlePageChange = (selectedPage: any) => {
✅

2023-07-19 22:15 UTC, zarinaazamatova commented on src/components/News/News.tsx
> +  const handlePageChange = (selectedPage: any) => {
✅

2023-07-19 22:16 UTC, zarinaazamatova commented on src/components/News/News.tsx
> +    async function fetchData() {
✅

2023-07-19 22:18 UTC, zarinaazamatova commented on src/components/News/News.tsx
> +        <Link href="./" style={{ textDecoration: 'none', color: 'grey', fontSize: '12px' }}>
fixed in all components

2023-07-19 22:18 UTC, zarinaazamatova commented on src/components/News/News.tsx
> +          {news.map((e: any) => (
✅

2023-07-19 22:18 UTC, zarinaazamatova commented on src/components/News/News.tsx
> +  const pageSize: number = 16;
✅

2023-07-19 22:21 UTC, zarinaazamatova commented on src/components/News/Pagination/Pagination.tsx
> +  onPageChange: any;
✅

2023-07-19 22:21 UTC, zarinaazamatova commented on src/components/News/Pagination/Pagination.tsx
> +export const Pagination = ({ pageCount, onPageChange, selectedPage }: PaginationProps) => {
✅

2023-07-19 22:22 UTC, zarinaazamatova commented on src/components/News/News.tsx
> +export const News = () => {
✅

2023-07-19 22:22 UTC, zarinaazamatova commented on src/pages/index.tsx
> +  return <Layout />;
✅

2023-07-20 06:10 UTC, Alex-2kZharkov commented on src/components/News/News.styles.ts
> +  margin-bottom: 30px;
@zarinaazamatova Excellent , my friend!

2023-07-20 06:12 UTC, Alex-2kZharkov approved these changes

2023-07-20 08:09 UTC, merged