create contactUsWidget component and write test
zarinaazamatova/huawei_nextjs pull request #19
Opened 2023-07-19 23:14 UTC by Zhyldyz1501

@Alex-2kZharkov I decided to push this code and get comments from you and after it I will add css part.

2023-07-20 06:27 UTC, Alex-2kZharkov requested changes

2023-07-20 06:27 UTC, Alex-2kZharkov commented on src/components/ContactUsWidget/ContactUsWidget.styles.ts
> +    position: fixed;
I want you to try same thing for styles that I recently shared to Zarina https://medium.com/swlh/better-ways-to-organise-css-properties-9a066e7ded62

2023-07-20 06:27 UTC, Alex-2kZharkov commented on src/components/ContactUsWidget/components/ContactOptions.tsx
You have skipped `index.ts` file for this folder, please fix it and import in target file because it will look like so `/components/ContactOptions/ContactOptions` , you can remove duplicating part

2023-07-20 06:27 UTC, Alex-2kZharkov commented on src/components/ContactUsWidget/components/ContactOptions.test.tsx
> +    testOptions.forEach((option) => {
you don't need a cycle here because you have only 1 element in an array

2023-07-20 06:27 UTC, Alex-2kZharkov commented on src/components/ContactUsWidget/components/ContactOptions.test.tsx
> +    testOptions.forEach((option) => {
you don't need a cycle here because you have only 1 element in an array

2023-07-20 06:27 UTC, Alex-2kZharkov commented on src/components/ContactUsWidget/ContactUsWidget.test.tsx
> +    expect(screen.getByText('Contact Us')).toBeInTheDocument();
@zarinaazamatova What would you improve here in terms of readability?

2023-07-20 06:27 UTC, Alex-2kZharkov commented on src/components/ContactUsWidget/ContactUsWidget.test.tsx
> +    fireEvent.click(contactUsContainer);
use shouls use `userEvent`, see how Asel did that in here https://github.com/zarinaazamatova/huawei_nextjs/pull/16/files#diff-e178584ca64509360860225b902067e074bdf844eeccee5ec6846c80ec15d1c8

2023-07-20 06:27 UTC, Alex-2kZharkov commented on src/components/ContactUsWidget/ContactUsWidget.test.tsx
> +    fireEvent.click(contactUsContainer);
just add 1 empty line before and after each click

2023-07-20 06:27 UTC, Alex-2kZharkov commented on src/components/ContactUsWidget/ContactUsWidget.tsx
> +  const toggleWidget = () => {
What return type you should use for this function? Please, set it

2023-07-20 06:27 UTC, Alex-2kZharkov commented on src/components/ContactUsWidget/ContactUsWidget.tsx
> +React.memo(ContactUsWidget);
intentions are correct but you made incorrect implementation. It should be `export const ContactUsWidget = memo(({ options }: ContactUsWidgetProps) => {.....})`. Otherwise, memo version of component is left on the line 24

2023-07-20 09:46 UTC, zarinaazamatova commented on src/components/ContactUsWidget/ContactUsWidget.test.tsx
> +    expect(screen.getByText('Contact Us')).toBeInTheDocument();
add 1 empty line before the first "expect"

2023-07-24 13:24 UTC, Alex-2kZharkov reviewed
not all changes have been sent

2023-07-24 13:24 UTC, Alex-2kZharkov commented on src/components/ContactUsWidget/ContactUsWidget.test.tsx
> +    expect(screen.getByText('Contact Us')).toBeInTheDocument();
absolutely!

2023-08-09 14:03 UTC, Alex-2kZharkov approved these changes

2023-08-09 14:04 UTC, merged