Feature/hnj 22 creating logic for changing cities
zarinaazamatova/huawei_nextjs pull request #22
Opened 2023-07-25 19:34 UTC by zarinaazamatova

As part of the implementation of the city selection, modal windows were created. The value of the selected city is stored in cookies. The list of cities for different tabs is displayed depending on the selected tab.

2023-07-29 18:30 UTC, Alex-2kZharkov requested changes

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/components/Header/components/Location/Location.tsx
> +export const Location: React.FC = (): ReactElement => {
`FC` is old thing better not to use it

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/components/Header/components/Location/Location.tsx
> +  if (!showCity) {
put it in the end before the `return` with content + return null, not <></> as it is more readable and logical

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/components/Header/components/Location/Location.tsx
> +  const handleImageHover = () => {
better to name this function different to handle 2 cases and remove the function below. you can do setIsOpen(prevState => !prevState). That solve 2 cases

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/components/Header/components/Location/Location.tsx
> +  const handleCloseModal = () => {
set return type to void for all of these functions

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/components/Header/components/Location/Location.tsx
> +  const city = getCookie('city');
one more moment. You better have some constant (global constant `src/constants/cookies` COOKIES, and then use this variable here. It will be easier to track changes and usages of cookies

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/features/cities/city.styles.ts
> +    position: absolute;
Good! You really are remembering in a great details that order of styles like position are first, then display etc. I am truly proud of you!

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/features/cities/city.test.tsx
> +  it('should render modal window', async () => {
I dont think you need `async` here

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/features/cities/city.tsx
> +export const Modal: React.FC<ModalWindowProps> = ({ isOpen, onClose, onOpenCities }) => {
remove FC https://www.reddit.com/r/reactjs/comments/wjq51d/is_reactfc_not_recommended_what_are_other/

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/features/cities/city.tsx
> +  const city = getCookie('city') ?? 'Москва';
use new constant here for `city` as well

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/features/cities/components/cities/Cities.hook.ts
> +export const useOutsideClick = (ref: RefObject<HTMLElement>, onClose: () => void) => {
don't forget about setting return type

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/features/cities/components/cities/Cities.hook.ts
> +    const handleDocumentClick = (event: MouseEvent) => {
return type

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/features/cities/components/cities/Cities.hook.ts
Cities.hook**s**.ts

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/features/cities/components/cities/Cities.tsx
> +export const Cities: React.FC<TabComponentProps> = ({ isOpenCities, onCloseCities }) => {
FC + return type for component

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/features/cities/components/cities/Cities.tsx
> +  const [activeTab, setActiveTab] = useState('moscowMO');
Create a enum for such moscowMO

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/features/cities/components/cities/Cities.tsx
> +  const allCities = useMemo(() => {
call it citiesList

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/features/cities/components/cities/Cities.tsx
> +/* styled.div`
please remove comments

2023-07-29 18:30 UTC, Alex-2kZharkov commented on src/features/cities/components/cities/api.ts
> +export const fetchNews = async (currentPage: number, pageSize: number): Promise<NewsItem[]> => {
don't forget to remove this one

2023-08-03 11:53 UTC, zarinaazamatova commented on src/components/Header/components/Location/Location.tsx
> +export const Location: React.FC = (): ReactElement => {
✅

2023-08-03 11:53 UTC, zarinaazamatova commented on src/components/Header/components/Location/Location.tsx
> +  if (!showCity) {
✅

2023-08-03 11:53 UTC, zarinaazamatova commented on src/components/Header/components/Location/Location.tsx
> +  const handleImageHover = () => {
✅

2023-08-03 11:53 UTC, zarinaazamatova commented on src/components/Header/components/Location/Location.tsx
> +  const handleCloseModal = () => {
✅

2023-08-03 11:54 UTC, zarinaazamatova commented on src/components/Header/components/Location/Location.tsx
> +  const city = getCookie('city');
✅

2023-08-03 11:54 UTC, zarinaazamatova commented on src/features/cities/city.styles.ts
> +    position: absolute;
✅

2023-08-03 11:54 UTC, zarinaazamatova commented on src/features/cities/city.test.tsx
> +  it('should render modal window', async () => {
✅

2023-08-03 11:54 UTC, zarinaazamatova commented on src/features/cities/city.tsx
> +export const Modal: React.FC<ModalWindowProps> = ({ isOpen, onClose, onOpenCities }) => {
✅

2023-08-03 11:54 UTC, zarinaazamatova commented on src/features/cities/city.tsx
> +  const city = getCookie('city') ?? 'Москва';
✅

2023-08-03 11:54 UTC, zarinaazamatova commented on src/features/cities/components/cities/Cities.hook.ts
> +export const useOutsideClick = (ref: RefObject<HTMLElement>, onClose: () => void) => {
✅

2023-08-03 11:54 UTC, zarinaazamatova commented on src/features/cities/components/cities/Cities.hook.ts
> +    const handleDocumentClick = (event: MouseEvent) => {
✅

2023-08-03 11:55 UTC, zarinaazamatova commented on src/features/cities/components/cities/Cities.hook.ts
✅

2023-08-03 11:55 UTC, zarinaazamatova commented on src/features/cities/components/cities/Cities.tsx
> +export const Cities: React.FC<TabComponentProps> = ({ isOpenCities, onCloseCities }) => {
✅

2023-08-03 11:55 UTC, zarinaazamatova commented on src/features/cities/components/cities/Cities.tsx
> +  const [activeTab, setActiveTab] = useState('moscowMO');
✅

2023-08-03 11:55 UTC, zarinaazamatova commented on src/features/cities/components/cities/Cities.tsx
> +  const allCities = useMemo(() => {
✅

2023-08-03 11:55 UTC, zarinaazamatova commented on src/features/cities/components/cities/Cities.tsx
> +/* styled.div`
✅

2023-08-03 11:55 UTC, zarinaazamatova commented on src/features/cities/components/cities/api.ts
> +export const fetchNews = async (currentPage: number, pageSize: number): Promise<NewsItem[]> => {
✅

2023-08-10 04:19 UTC, Alex-2kZharkov approved these changes

2023-08-11 18:05 UTC, merged