Feature/hnj 25 breadcrumbs
zarinaazamatova/huawei_nextjs pull request #23
Opened 2023-07-28 13:28 UTC by Aselia-K

This pull request adds a new BreadCrumbs component to the project, which dynamically generates the breadcrumb links based on the current URL path. The component utilizes  useRouter hook to retrieve the current pathname and then processes it to create the breadcrumb segments.

The BreadCrumbs component takes the current pathname, splits it into individual segments, and calculates cumulative paths for each segment. The cumulative paths are used to generate clickable breadcrumb links that allow users to navigate back to previous parent components.

2023-07-29 18:13 UTC, Alex-2kZharkov requested changes

2023-07-29 18:13 UTC, Alex-2kZharkov commented on src/components/BreadCrumbs/BreadCrumbs.test.tsx
> +    expect(screen.queryByText('Grandchild')).not.toBeInTheDocument();
excellent test!

2023-07-29 18:13 UTC, Alex-2kZharkov commented on src/components/BreadCrumbs/BreadCrumbs.tsx
> +export const BreadCrumbs = () => {
set return type to ReactElement

2023-07-29 18:13 UTC, Alex-2kZharkov commented on src/components/BreadCrumbs/BreadCrumbs.tsx
> +  const { pathname } = useRouter();
I have a suggestion for you. Create custom hook called `useBreadCrumbsPath` and put it into the `BreadCrumbs.hooks.ts` file. It will be less verbose in your component and separate concerns

2023-07-29 18:13 UTC, Alex-2kZharkov commented on src/components/BreadCrumbs/BreadCrumbs.tsx
> +  return (
always have 1 empty line before return. It reads better

2023-07-29 18:13 UTC, Alex-2kZharkov commented on src/components/BreadCrumbs/BreadCrumbs.tsx
> +        {cumulativePathsArray.map((pathSegment, index) => {
please, set types for .map arguments

2023-07-29 18:13 UTC, Alex-2kZharkov commented on src/components/BreadCrumbs/BreadCrumbs.tsx
> +    <ThemeProvider theme={defaultTheme}>
You sure we need ThemeProvider here again? It should be used once (we used it), and then all child components do not need to write again

2023-07-29 18:13 UTC, Alex-2kZharkov commented on src/components/BreadCrumbs/BreadCrumbsData.ts
> +};
you can add `as const` at the end of this object. Read more here what it will do to your code https://blog.logrocket.com/complete-guide-const-assertions-typescript/

2023-07-29 18:13 UTC, Alex-2kZharkov commented on src/components/BreadCrumbs/BreadCrumbsData.ts
call this file BreadCrumbs.constants.ts

2023-07-30 22:36 UTC, Aselia-K commented on src/components/BreadCrumbs/BreadCrumbs.test.tsx
> +    expect(screen.queryByText('Grandchild')).not.toBeInTheDocument();
Thank you)

2023-07-30 22:39 UTC, Aselia-K commented on src/components/BreadCrumbs/BreadCrumbs.tsx
> +export const BreadCrumbs = () => {
Done

2023-07-30 22:40 UTC, Aselia-K commented on src/components/BreadCrumbs/BreadCrumbs.tsx
> +  return (
done

2023-07-30 22:42 UTC, Aselia-K commented on src/components/BreadCrumbs/BreadCrumbs.tsx
> +        {cumulativePathsArray.map((pathSegment, index) => {
done

2023-07-30 22:48 UTC, Aselia-K commented on src/components/BreadCrumbs/BreadCrumbs.tsx
> +    <ThemeProvider theme={defaultTheme}>
If I remove it, tests are failing: 

TypeError: Cannot read properties of undefined (reading 'roboto')
      3 | export const StyledBreadCrumbsList = styled.ul`
    > 4 |   font-family: ${({ theme }) => theme.fontFamily.roboto[1]};

Had the same issue with the Footer component, and we decided to wrap it with theme provider back then.

2023-07-30 22:49 UTC, Aselia-K commented on src/components/BreadCrumbs/BreadCrumbsData.ts
> +};
done

2023-07-30 22:50 UTC, Aselia-K commented on src/components/BreadCrumbs/BreadCrumbsData.ts
done

2023-07-30 23:09 UTC, Aselia-K commented on src/components/BreadCrumbs/BreadCrumbs.tsx
> +  const { pathname } = useRouter();
Great idea! Done

2023-08-10 04:07 UTC, Alex-2kZharkov commented on src/components/BreadCrumbs/BreadCrumbs.tsx
> +    <ThemeProvider theme={defaultTheme}>
https://github.com/zarinaazamatova/huawei_nextjs/assets/66321831/64c79996-3d31-4150-990a-705051ed6efd

![image](https://github.com/zarinaazamatova/huawei_nextjs/assets/66321831/1538a058-93fa-4a80-8d7c-7e2cbc983628)


Probably, you did not put `ThemeProvider` directly into test at first attempt

2023-08-10 04:08 UTC, Alex-2kZharkov commented on src/components/BreadCrumbs/BreadCrumbs.tsx
> +    <ThemeProvider theme={defaultTheme}>
+ your tests fail because of:
![image](https://github.com/zarinaazamatova/huawei_nextjs/assets/66321831/999e7f21-7513-4474-81f7-fb5ea5dd46cb)

2023-08-10 04:09 UTC, Alex-2kZharkov requested changes
one last comment

2023-08-17 10:57 UTC, Alex-2kZharkov approved these changes

2023-08-17 10:59 UTC, merged