Feature/hnj 32 creating benefits section
zarinaazamatova/huawei_nextjs pull request #26
Opened 2023-08-14 10:36 UTC by zarinaazamatova

A menu accordion was created for the implementation of the "Benefits" section. Menu is a vertically arranged list of different benefit information items. By default, the contents of each list are hidden. Clicking on a particular title will expand its content.
<img width="1306" alt="Screenshot 2023-08-14 at 12 24 14" src="https://github.com/zarinaazamatova/huawei_nextjs/assets/93516049/93d4dd5f-07f3-4f8f-a81c-69d4f60c8e51">

2023-08-16 13:51 UTC, Alex-2kZharkov requested changes

2023-08-16 13:51 UTC, Alex-2kZharkov commented on src/components/Accordion/Accordion.test.tsx
> +  it('correct opening and closing of sections', () => {
don't forget to start test from `should`

2023-08-16 13:51 UTC, Alex-2kZharkov commented on src/components/Accordion/Accordion.test.tsx
> +    fireEvent.click(getByText('Title 1'));
you should use `userEvent.click`, because we've downloaded it and used before

2023-08-16 13:51 UTC, Alex-2kZharkov commented on src/components/Accordion/Accordion.test.tsx
> +    expect(queryByText('Content 1')).toBeInTheDocument();
If you check for presence, it should be `getByText`

2023-08-16 13:51 UTC, Alex-2kZharkov commented on src/components/Layout/Benefits/Benefits.test.tsx
> +  Accordion: jest.fn(() => <div>Mocked Accordion</div>),
In general, you can skip mocking if the component does not ruin the test. It is always good to see how to work together

2023-08-20 12:46 UTC, zarinaazamatova commented on src/components/Accordion/Accordion.test.tsx
> +  it('correct opening and closing of sections', () => {
✅

2023-08-20 12:46 UTC, zarinaazamatova commented on src/components/Accordion/Accordion.test.tsx
> +    fireEvent.click(getByText('Title 1'));
✅

2023-08-20 12:46 UTC, zarinaazamatova commented on src/components/Accordion/Accordion.test.tsx
> +    expect(queryByText('Content 1')).toBeInTheDocument();
✅

2023-08-20 12:46 UTC, zarinaazamatova commented on src/components/Accordion/Accordion.test.tsx
> +    expect(queryByText('Content 2')).toBeInTheDocument();
✅

2023-08-20 12:46 UTC, zarinaazamatova commented on src/components/Layout/Benefits/Benefits.test.tsx
> +  Accordion: jest.fn(() => <div>Mocked Accordion</div>),
✅

2023-08-20 12:47 UTC, zarinaazamatova commented on src/components/Layout/Benefits/Benefits.styles.ts
✅

2023-08-20 12:47 UTC, zarinaazamatova commented on src/components/Accordion/Accordion.styled.ts
> +  width: 1000px;
✅

2023-08-22 07:40 UTC, Alex-2kZharkov approved these changes

2023-08-22 10:24 UTC, merged