Feature/hnj 6 styled components
zarinaazamatova/huawei_nextjs pull request #7
Opened 2023-06-17 09:44 UTC by zarinaazamatova

2023-06-19 09:36 UTC, Alex-2kZharkov requested changes

2023-06-19 09:36 UTC, Alex-2kZharkov commented on package.json
> -      "tsc --noEmit"
why did you remove `tsc --noEmit`? We want it to work for each commit😅

2023-06-19 09:36 UTC, Alex-2kZharkov commented on src/pages/_app.tsx
> +  <ThemeProvider theme={defaultTheme}>
Yes, everything is correct. The only thing that bothers me is incorrect formatting. Please, check that `vscode` uses our `prettier`

2023-06-19 09:36 UTC, Alex-2kZharkov commented on src/pages/index.tsx
> +const Title = styled.h1`
There is a convention to name elements after `styled` has been applied. It will `Styled` + a name of an element. In this case, it will be `StyledH1`

2023-06-19 09:36 UTC, Alex-2kZharkov commented on src/styles/theme.ts
> +      orange: '#fe5000',
better to call `secondary`

2023-06-19 09:36 UTC, Alex-2kZharkov commented on src/styles/theme.ts
> +      white: '#fff',
it is better to write it in the full version `#ffffff` because all other colors are written in full a notation

2023-06-19 09:36 UTC, Alex-2kZharkov commented on src/styles/theme.ts
> +        black: '#000',
Again: full color notation

2023-06-19 09:36 UTC, Alex-2kZharkov commented on src/styles/theme.ts
> +      dgrey: 'rgba(29,54,75,.5)',
I guess it is `darkGray`, then let's name it properly

2023-06-19 09:36 UTC, Alex-2kZharkov commented on src/styles/theme.ts
> +    colors: {
and we need one last color on this stage, the `accent`:
![image](https://github.com/zarinaazamatova/huawei_nextjs/assets/66321831/fd19cc11-d4ce-40c7-9b3f-b6b92197d8df)

2023-06-19 09:36 UTC, Alex-2kZharkov commented on src/styles/theme.ts
> +    // screens for a vast array of web-capable  browsers.
no need to add such a comments because they do not bring use to the code. Look at the `spacing`: we have section below called `spacing` and the comment does not tell anything new

2023-06-24 09:18 UTC, zarinaazamatova commented on package.json
> -      "tsc --noEmit"
✅

2023-06-24 09:18 UTC, zarinaazamatova commented on src/pages/_app.tsx
> +  <ThemeProvider theme={defaultTheme}>
✅

2023-06-24 09:18 UTC, zarinaazamatova commented on src/pages/index.tsx
> +const Title = styled.h1`
✅

2023-06-24 09:18 UTC, zarinaazamatova commented on src/styles/theme.ts
> +      orange: '#fe5000',
✅

2023-06-24 09:19 UTC, zarinaazamatova commented on src/styles/theme.ts
> +      white: '#fff',
✅

2023-06-24 09:19 UTC, zarinaazamatova commented on src/styles/theme.ts
> +        black: '#000',
✅

2023-06-24 09:19 UTC, zarinaazamatova commented on src/styles/theme.ts
> +      dgrey: 'rgba(29,54,75,.5)',
✅

2023-06-24 09:19 UTC, zarinaazamatova commented on src/styles/theme.ts
> +    colors: {
✅

2023-06-24 09:22 UTC, zarinaazamatova commented on src/styles/theme.ts
> +    // screens for a vast array of web-capable  browsers.
✅

2023-06-24 17:19 UTC, Alex-2kZharkov approved these changes

2023-06-24 17:22 UTC, merged