Fix/HNJ-16 improve pre push hook
zarinaazamatova/huawei_nextjs pull request #8
Opened 2023-06-18 21:59 UTC by zarinaazamatova

2023-06-19 07:44 UTC, Alex-2kZharkov requested changes

2023-06-19 07:44 UTC, Alex-2kZharkov commented on package.json
> +    "validate-branch-name": "^1.3.0"
It is great that you've found a way to do it with some library but we can do it even without any libraries at all. The only thing that we need is a bout of knowledge of `bash` knowledge.

We will add it directly to the `pre-push` hook:
```
BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_PATTERN="^(feature|fix|test|release)\/HNJ-[0-9]+_[a-zA-Z0-9-]+$"

if [[ ! "$BRANCH_NAME" =~ $BRANCH_PATTERN ]]; then
  echo "Invalid branch name format. Branch name should be in the format of <ticket type>/EVWSNX-<number>_<description>"
  exit 1
else
    echo "Branch name is valid"
fi
```

2023-06-19 07:44 UTC, Alex-2kZharkov commented on package.json
> +    "validate-branch-name": "^1.3.0"
Here the `BRANCH_NAME` allows you to get the current branch name. The `BRANCH_PATTERN="^(feature|fix|test|release)\/HNJ-[0-9]+_[a-zA-Z0-9-]+$"` defines the `regex` rule

Then you test it inside `if` statement and throw an with `exit 1` if the branch has incorrect name. The `echo` is like `console.log`. You can feed chat gpt with snippet and ask him to `explain what is it and what does it do`

2023-06-19 07:44 UTC, Alex-2kZharkov commented on .validate-branch-namerc
> +{
Don't forget to remove this file and corresponding package from `package.json` via `npm uninstall` command

2023-06-19 09:34 UTC, zarinaazamatova commented on package.json
> +    "validate-branch-name": "^1.3.0"
✅

2023-06-19 09:40 UTC, zarinaazamatova commented on .validate-branch-namerc
> +{
✅

2023-06-20 05:53 UTC, Alex-2kZharkov requested changes

2023-06-20 05:53 UTC, Alex-2kZharkov commented on package.json
> +    "check-branch-name": "chmod 700 .husky/check_branch_naming.sh && sh .husky/check_branch_naming.sh"
please remove this command as well

2023-06-20 05:53 UTC, Alex-2kZharkov commented on .husky/pre-push
> +BRANCH_PATTERN="^(feature|fix|test|release)/HNJ-[0-9]+-[a-zA-Z0-9-]+$"
There is a inconsistency. You ask to write branch name like `fix/HNJ-16-improve-pre-push-hook` with `-` between `16` and the next part of description, but the example on line 8 shows `_` is used. Please, select one option and stick to it

2023-06-20 05:53 UTC, Alex-2kZharkov commented on package.json
> +    "validate-branch-name": "^1.3.0"
good

2023-06-24 16:42 UTC, zarinaazamatova commented on package.json
> +    "check-branch-name": "chmod 700 .husky/check_branch_naming.sh && sh .husky/check_branch_naming.sh"
✅

2023-06-24 16:42 UTC, zarinaazamatova commented on .husky/pre-push
> +BRANCH_PATTERN="^(feature|fix|test|release)/HNJ-[0-9]+-[a-zA-Z0-9-]+$"
✅

2023-06-24 17:26 UTC, Alex-2kZharkov approved these changes

2023-06-24 17:28 UTC, merged